### ISSUE TITLE
turbofan support

### ISSUE THREAD

**Issue by brendangregg** [nodejs/llnode#126]
Does anything break with the new v8 turbofan compiler? Does llnode need changes to support it? I don't know myself, but am filing a ticket as a reminder that we need to check.

**Comment by joyeecheung** [comment]
Related and fixed: https://github.com/nodejs/llnode/issues/117

After using this patch (with a patched version of Node.js since https://chromium-review.googlesource.com/c/618986 has not landed in upstream yet), I have still been seeing evaluation failures when analyzing coredumps generated by Node.js v8.4.0. Will get to it later when I have a bit more time.

**Comment by cjihrig** [comment]
@joyeecheung see #130. I'm pretty close to having the test suite pass on V8 6.1.

**Comment by joyeecheung** [comment]
@cjihrig Interesting, have not tried 6.1 yet. I will take a look.
