### ISSUE TITLE
llnode doesn't support lldb 6.0 now

### ISSUE THREAD

**Issue by langhuihui** [nodejs/llnode#133]
function getLinuxVersion(lldbExe) {

  var lldbStr;
  try {
    lldbStr = child_process.execFileSync(lldbExe, ['-v']).toString();
  } catch (err) {
    return undefined;
  }
  // Ignore minor revisions like 3.8.1
  if (lldbStr.indexOf('version 4.0') > 0) {
    return '4.0';
  } else if (lldbStr.indexOf('version 3.9') > 0) {
    return '3.9';
  } else if (lldbStr.indexOf('version 3.8') > 0) {
    return '3.8';
  } else if (lldbStr.indexOf('version 3.7') > 0) {
    return '3.7';
  } if (lldbStr.indexOf('version 3.6') > 0) {
    return '3.6';
  } if (lldbStr.indexOf('version 3.5') > 0) {
    return '3.5';
  }
  return undefined;
}

need improve the code

**Comment by bnoordhuis** [comment]
There is no lldb 6.0, the 4.0 series are the latest at this time.

**Comment by hhellyer** [comment]
v5.0 is due for release soon and the release_50 branch now exists in git, we should fix this - it's useful for anyone who compiles lldb themselves. (Like me!)

I'll try to do a PR later on.

**Comment by langhuihui** [comment]
@hhellyer yes. I am sure that lldb version shows 6.0 when I  compiles lldb.

**Comment by bnoordhuis** [comment]
PR welcome but the point remains that 4.0 is the latest release and this bug report is invalid.  I think it's perfectly sane for the install script to fail on prerelease versions of lldb.

@langhuihui You are using lldb from git master.  I wouldn't recommend that in conjunction with llnode - we don't test that and can't guarantee it works.  Use a release version.

**Comment by hhellyer** [comment]
I won't re-open again as otherwise this will turn into a game of ping-pong but:
* If we hit problems opening particular core dumps we would recommend users try the latest version of lldb with llnode as that's where any fix would arrive first. (Some of those fixes have been from us.)
* lldb-5.0 can be installed from http://apt.llvm.org/ now. Users can get it there before it hits the main repositories both pre-release and once it's formally released.
* The lldb team make a big effort to keep the C++ API compatible across releases and enforce rules when adding to it that ensure it works. (I'd normally be wary of this but the wider llvm project does produce a C++ compiler so I suspect they know what they are are doing.)
