### ISSUE TITLE
llnode don't support nodejs v12

### ISSUE THREAD

**Issue by phantom9999** [nodejs/llnode#328]

**Comment by mmarchini** [comment]
https://github.com/nodejs/llnode/pull/318 have most of the changes needed for llnode to work with future v12 releases (we still need https://github.com/nodejs/node/pull/30870 to be merged and released on Node.js v12, otherwise llnode won't have enough information to reverse engineer v12 core dumps/memory)

**Comment by mmarchini** [comment]
Closing as llnode 3.0.0 supports Node.js v12.x
