### ISSUE TITLE
npm i llnode

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/llnode#53]
I think this should be possible to install on a global install via npm scripts, @indutny is there any reason you didn't go this route?

**Comment by indutny** [comment]
I don't mind if someone will make it work :wink:

**Comment by hhellyer** [comment]
It would definitely be nice to have a simpler way to install llnode, especially on Linux.
I'm not 100% sure on using npm to install things that aren't going to be node code but there's also the possibility of adding a javascript API to llnode in which case it would make more sense.

It could write a plugin load command to ~/.lldbinit instead of needing root access to install the plugin in lldb's plugin directory. There will probably be issues around using the right version of lldb, on ubuntu it's possible to have multiple versions installed as lldb-3.8, lldb-3.9.

I'm happy to take a look at doing this. Should we reserve the name llnode on npmjs.org?

**Comment by indutny** [comment]
Sure, go ahead!

**Comment by Fishrock123** [comment]
Two things: make sure you register with a version that `llnode` has not used, like 0.0.0. Also, we should publish some basic install instructions there in the mean time.

**Comment by hhellyer** [comment]
I've grabbed the llnode npm name. I've added @indutny as a collaborator. (Assuming that isn't someone else with the same picture on npmjs.org.)
I assume the npm installer should work for Mac and Linux (as a minimum) and I'll probably look at what the brew installer is doing.

**Comment by indutny** [comment]
(Yep, that's me)

**Comment by hhellyer** [comment]
@indutny Making progress on this but I've got a question, why did you use llnode.gyp instead of binding.gyp?

The background to this is that for some reason npm doesn't copy llnode.gyp unless you specify it explicitly (and then have to specify everything to copy). I think there's something special about <packagename>.gyp but I don't know what. Also you can't stop npm copying binding.gyp.
I may end up changing the build process slightly, I'm also trying to figure out if it's possibly to use the gyp packaged with npm rather than cloning it during the build process so the only thing that may need cloning is the lldb headers.

**Comment by hhellyer** [comment]
I've pushed a branch https://github.com/hhellyer/llnode/tree/npm_prototype which you are welcome to try however it's not final, part of the reason for pushing to github is to make it easy to test it on more machines.

**Comment by indutny** [comment]
@hhellyer splendid! Will take a look.

btw, I forgot to mention it, but I have solved similar problem in bud: https://github.com/indutny/bud

**Comment by hhellyer** [comment]
Cool, I've flattened the branch a bit and copied your solution to <package>.gyp. I still need a better solution for not cloning gyp than my current one but I'm going to do some testing with different installs of lldb first in case I hit any show stoppers.

**Comment by indutny** [comment]
@hhellyer looks pretty cool except for the JS code style ;) Feel free to open PR whenever you'll feel that it is ready and we will collaborate there on it!

Thank you

**Comment by hhellyer** [comment]
I've updated the prototype, if anyone wants to try it. It's a bit neater and now outputs the lldb command to use to load the plugin.

I've a couple of questions before I turn it into a PR:
- Is there any use in putting up this up as an npm, for example with a version of 0.0.1, for testing? (Does that behave differently to a git install?)
- Does anyone have a better idea for locating gyp? (Better than my use of npm explore in configure.js!) I'm trying to avoid having to download if as it is possible to avoid doing any git clones if the lldb headers are already on the machine.

It can be installed from git with:
`npm install hhellyer/llnode#npm_prototype`

**Comment by hhellyer** [comment]
@Fishrock123 - Can I close this now? (Or can you?)

**Comment by davidmarkclements** [comment]
just to note, I put this together for Mac and Ubuntu a few months ago

It's published to npm

```sh
$ npm install llnode-setup
```

Uses a slightly different approach - detects OS and then runs the install steps for that OS

Extendable by adding .sh files and adding detection to the `cmd.js` file

If you're thinking there's a more suitable approach, I'll also happy donate `llnode-setup`

(cc @lucamaraschi)

**Comment by davidmarkclements** [comment]
oh wait - the github readme says you can `npm install llnode` 
- but the npm readme hasn't been updated

**Comment by rnchamberlain** [comment]
@davidmarkclements you are right, see https://github.com/nodejs/llnode/pull/65, the readme was updated to document the npm install, but we need a npm publish for that to show up

@indutny @hhellyer see https://github.com/nodejs/llnode/issues/49, want me to do the changelog/version/npm publish?

**Comment by indutny** [comment]
@rnchamberlain that would be awesome! Thank you!

**Comment by rnchamberlain** [comment]
@indutny @hhellyer right oh, will do. I'll need the powers on llnode to push the changelog and the release/tag, also on https://www.npmjs.com/package/llnode to do the publish - thanks.

**Comment by bnoordhuis** [comment]
Closing, fixed by #60.  #77 is the tracking issue for `npm install -g llnode`.
