### ISSUE TITLE
Advice on how to debug llnode plugin?

### ISSUE THREAD

**Issue by evantorrie** [nodejs/llnode#63]
This isn't so much an issue, as just a request for advice.

I'm interested in hacking on llnode, but I'm brand new to lldb.  Do you have any advice on how to debug the llnode extension while it's running inside lldb on a node corefile.  I did a search for debugging lldb under lldb, but didn't turn up anything obvious.

Thanks.

**Comment by indutny** [comment]
Hello!

Thank you for your interest.

It is pretty easy to debug it:

1. just build it in Debug mode
2. open lldb and run `plugin load /path/to/debug/llnode.dylib`
3. open another `lldb -p <pid of first lldb>`
4. set breakpoint to some of llnode's functions
5. run `continue` in second lldb
6. use first lldb

**Comment by evantorrie** [comment]
I've been trying on Linux -- and not so successful (e.g. lldb coredumping).

Let me try on MacOSX.

**Comment by hhellyer** [comment]
@evantorrie - It could be a mismatch between the lldb headers you used and the version of lldb you are running. That might make this a good test case for trying the npm installer:
https://www.npmjs.com/package/llnode

It should print out the choices it makes about what to download (I think I made it verbose enough) so that might help with configuring a clone from github to do a local build later on.

**Comment by indutny** [comment]
Closing this, please re-open if it is still relevant.
